project_id = "usblrulkcgucxtkhugck"

[functions.send-gmail]
verify_jwt = false

[functions.generate-personalized-email]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.generate-booking-linen-order]
verify_jwt = false