-- Disable RLS on all tables and drop existing policies

-- Drop all existing RLS policies
DROP POLICY IF EXISTS "Allow all operations on alpine_activities" ON alpine_activities;
DROP POLICY IF EXISTS "Allow all operations for authenticated users" ON house_inventory;
DROP POLICY IF EXISTS "Users can manage preview edits" ON ical_preview_edits;
DROP POLICY IF EXISTS "Allow all operations on linen_orders" ON linen_orders;
DROP POLICY IF EXISTS "Laundry providers can view linen requirements" ON linen_requirements;
DROP POLICY IF EXISTS "Allow all operations on linen_set_definitions" ON linen_set_definitions;
DROP POLICY IF EXISTS "Admins can manage provider tokens" ON provider_tokens;
DROP POLICY IF EXISTS "saved_places_select_own" ON saved_places;
DROP POLICY IF EXISTS "saved_places_insert_own" ON saved_places;
DROP POLICY IF EXISTS "saved_places_update_own" ON saved_places;
DROP POLICY IF EXISTS "saved_places_delete_own" ON saved_places;
DROP POLICY IF EXISTS "service_providers_select_policy" ON service_providers;
DROP POLICY IF EXISTS "service_providers_insert_policy" ON service_providers;
DROP POLICY IF EXISTS "service_providers_update_policy" ON service_providers;
DROP POLICY IF EXISTS "service_providers_delete_policy" ON service_providers;
DROP POLICY IF EXISTS "Service providers can access their own portal data" ON service_providers;
DROP POLICY IF EXISTS "Admins can manage all tasks" ON service_tasks;
DROP POLICY IF EXISTS "service_tasks_select_policy" ON service_tasks;
DROP POLICY IF EXISTS "service_tasks_update_policy" ON service_tasks;
DROP POLICY IF EXISTS "service_tasks_delete_policy" ON service_tasks;
DROP POLICY IF EXISTS "trip_activities_select_own" ON trip_activities;
DROP POLICY IF EXISTS "trip_activities_insert_own" ON trip_activities;
DROP POLICY IF EXISTS "trip_activities_update_own" ON trip_activities;
DROP POLICY IF EXISTS "trip_activities_delete_own" ON trip_activities;
DROP POLICY IF EXISTS "user_profiles_select_own" ON user_profiles;
DROP POLICY IF EXISTS "user_profiles_insert_own" ON user_profiles;
DROP POLICY IF EXISTS "user_profiles_update_own" ON user_profiles;
DROP POLICY IF EXISTS "user_profiles_delete_own" ON user_profiles;
DROP POLICY IF EXISTS "vacation_trips_select_own" ON vacation_trips;
DROP POLICY IF EXISTS "vacation_trips_insert_own" ON vacation_trips;
DROP POLICY IF EXISTS "vacation_trips_update_own" ON vacation_trips;
DROP POLICY IF EXISTS "vacation_trips_delete_own" ON vacation_trips;

-- Disable RLS on all tables
ALTER TABLE activity_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE alpine_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE blocked_bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_confirmations DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE day_trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE house_cleaning_instructions DISABLE ROW LEVEL SECURITY;
ALTER TABLE house_ical_sources DISABLE ROW LEVEL SECURITY;
ALTER TABLE house_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE houses DISABLE ROW LEVEL SECURITY;
ALTER TABLE ical_preview_edits DISABLE ROW LEVEL SECURITY;
ALTER TABLE laundry_confirmations DISABLE ROW LEVEL SECURITY;
ALTER TABLE laundry_order_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE laundry_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE laundry_staff DISABLE ROW LEVEL SECURITY;
ALTER TABLE linen_orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE linen_requirements DISABLE ROW LEVEL SECURITY;
ALTER TABLE linen_set_definitions DISABLE ROW LEVEL SECURITY;
ALTER TABLE linen_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE provider_tokens DISABLE ROW LEVEL SECURITY;
ALTER TABLE route_cache DISABLE ROW LEVEL SECURITY;
ALTER TABLE saved_places DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_providers DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE trip_activities DISABLE ROW LEVEL SECURITY;
ALTER TABLE trip_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE vacation_trips DISABLE ROW LEVEL SECURITY;
ALTER TABLE weather_cache DISABLE ROW LEVEL SECURITY;